### ISSUE TITLE
[Feature Request] Offer Litecoin Address Resolution

### ISSUE THREAD

**Issue by kcw-grunt** [unstoppabledomains/resolution-java#15]
## Request
 Though this repo supports BTC and ETH address resolution it would be ideal to offer the same functionality for Litecoin (Ł).

**Comment by mvlabat** [comment]
Hi! Thanks for opening an issue. Our library already supports other currencies, including Litecoin (LTC). You can see that the `addr` method accepts any string as a `ticker`, it isn't limited to accept only BTC or ETH. If you have any troubles with resolving LTC addresses of your domains, please let us know.

Meanwhile, we'll try to update our readme to make this clearer.

**Comment by mvlabat** [comment]
I'll close this issue due to inactivity. Please feel to comment here or open another one if you have any problems with resolution.
