### ISSUE TITLE
jitpack release canot be resolved because build error

### ISSUE THREAD

**Issue by NateRobinson** [unstoppabledomains/resolution-java#73]
![截屏2022-05-23 16 10 00](https://user-images.githubusercontent.com/12446758/169773872-4003befc-be79-4767-b054-9daf17bd3b43.png)

https://jitpack.io/com/github/unstoppabledomains/resolution-java/v5.0.0/build.log

https://jitpack.io/#unstoppabledomains/resolution-java/Tag

**Comment by DancingAxolotl** [comment]
Hey @NateRobinson! Thanks for reaching out!
This should be fixed with v6.0.0. Let us know if you run into any other issues.

If you need a legacy version of the library, you can grab it from [maven](https://search.maven.org/artifact/com.unstoppabledomains/resolution).
