### ISSUE TITLE
Does v5.0.0 support domains like .eth?

### ISSUE THREAD

**Issue by shreyanshp** [unstoppabledomains/resolution-java#74]
Curious to know, cause we are using v1.13.x and thinking of bump to v5, however I can see the library dropped support for ens. Wondering if that adversely affects support for .eth or does it completely drop the support for .eth?

**Comment by DancingAxolotl** [comment]
Hey @shreyanshp! Sorry for taking a while to respond.
You are right, v5.0.0 dropped ENS support including ENS domains such as `.eth` and `.xyz`. But we intend to support options for other naming services in the future.
The latest version with ENS support is [v4.1.0](https://github.com/unstoppabledomains/resolution-java/releases/tag/v4.1.0). It will not receive new features, but it includes UNS and L2 support so it may be worth the upgrade anyway.

Let me know if you have any other questions. Also feel free to join our [discord](https://discord.com/invite/JWrEAAbp6R) and ask questions there.
